-- SQL file to create the invoices table
CREATE TABLE IF NOT EXISTS `invoices` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `sender_citizenid` varchar(50) NOT NULL,
    `sender_name` varchar(100) NOT NULL,
    `sender_type` enum('player', 'business') NOT NULL DEFAULT 'player',
    `sender_business_id` int(11) DEFAULT NULL,
    `sender_business_name` varchar(100) DEFAULT NULL,
    `receiver_citizenid` varchar(50) NOT NULL,
    `receiver_name` varchar(100) NOT NULL,
    `receiver_type` enum('player', 'business') NOT NULL DEFAULT 'player',
    `receiver_business_id` int(11) DEFAULT NULL,
    `receiver_business_name` varchar(100) DEFAULT NULL,
    `amount` decimal(10, 2) NOT NULL,
    `description` text NOT NULL,
    `tax_rate` decimal(5, 4) NOT NULL DEFAULT 0.1000,
    `invoice_number` varchar(50) DEFAULT NULL,
    `due_date` timestamp NULL DEFAULT NULL,
    `status` enum('pending', 'paid', 'expired', 'cancelled') NOT NULL DEFAULT 'pending',
    `payment_method` enum('cash', 'bank', 'business') DEFAULT 'bank',
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `expires_at` timestamp NULL DEFAULT NULL,
    `paid_at` timestamp NULL DEFAULT NULL,
    `notes` text DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `sender_citizenid` (`sender_citizenid`),
    KEY `receiver_citizenid` (`receiver_citizenid`),
    KEY `sender_business_id` (`sender_business_id`),
    KEY `receiver_business_id` (`receiver_business_id`),
    KEY `status` (`status`),
    KEY `created_at` (`created_at`),
    KEY `invoice_number` (`invoice_number`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- Create businesses table if it doesn't exist (for basic business support)
CREATE TABLE IF NOT EXISTS `businesses` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `name` varchar(100) NOT NULL,
    `owner_citizenid` varchar(50) NOT NULL,
    `business_type` varchar(50) DEFAULT NULL,
    `tax_id` varchar(50) DEFAULT NULL,
    `bank_account` varchar(50) DEFAULT NULL,
    `phone` varchar(20) DEFAULT NULL,
    `email` varchar(100) DEFAULT NULL,
    `address` text DEFAULT NULL,
    `status` enum('active', 'inactive', 'suspended') NOT NULL DEFAULT 'active',
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `owner_citizenid` (`owner_citizenid`),
    KEY `status` (`status`),
    UNIQUE KEY `name` (`name`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;